#!/bin/bash
set -e
apt -y install -y dirmngr
apt-key adv --keyserver pool.sks-keyservers.net --recv-keys 5072E1F5
# Note: key 5072E1F5 is MySQL official's (always double check!)
echo "deb http://repo.mysql.com/apt/debian $(lsb_release -sc) mysql-8.0" | \
    sudo tee /etc/apt/sources.list.d/mysql80.list
apt -y update
debconf-set-selections <<< \
  "mysql-community-server mysql-community-server/root-pass password tiger"

debconf-set-selections <<< \
  "mysql-community-server mysql-community-server/re-root-pass password tiger"

debconf-set-selections <<< \
  "mysql-community-server mysql-server/default-auth-override select Use Legacy Authentication Method (Retain MySQL 5.x Compatibility)"

DEBIAN_FRONTEND=noninteractive apt -y install mysql-server libmysqlclient-dev
