on:
  push:
    branches:
      - master
      - main
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  base:
    runs-on: [ubuntu-20.04]
    steps:
      - name: enable experimental docker features
        run: |
          sudo bash -c 'echo "{ \"cgroup-parent\": \"/actions_job\",\"experimental\":true}" > /etc/docker/daemon.json'
          sudo service docker restart
          docker version -f '{{.Server.Experimental}}'
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: build base image
        run: |
          cd image && ruby auto_build.rb base
      - name: build test_build image
        run: |
          cd image && ruby auto_build.rb bamzooka_test_build
      - name: run specs
        run: |
          docker run --rm -e RUBY_ONLY=1 -e USE_TURBO=1 -e SKIP_PLUGINS=1 -e SKIP_LINT=1 bamzooka/bamzooka_test:build
      - name: push to dockerhub
        if: success() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        env:
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          TAG=`date +%Y%m%d-%H%M`
          docker tag bamzooka/base:build bamzooka/base:2.0.$TAG
          docker tag bamzooka/base:build bamzooka/base:release
          docker login --username bamzookabuild --password $DOCKERHUB_PASSWORD
          docker push bamzooka/base:release
          docker push bamzooka/base:2.0.$TAG
  test:
    runs-on: [ubuntu-20.04]
    needs: base
    steps:
      - name: enable experimental docker features
        run: |
          sudo bash -c 'echo "{ \"cgroup-parent\": \"/actions_job\",\"experimental\":true}" > /etc/docker/daemon.json'
          sudo service docker restart
          docker version -f '{{.Server.Experimental}}'
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: build bamzooka_test image
        run: |
          cd image && ruby auto_build.rb bamzooka_test_public
      - name: push to dockerhub
        if: success() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        env:
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker login --username bamzookabuild --password $DOCKERHUB_PASSWORD
          docker push bamzooka/bamzooka_test:release
  dev:
    runs-on: [ubuntu-20.04]
    needs: base
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: build bamzooka_dev image
        run: |
          cd image && ruby auto_build.rb bamzooka_dev
      - name: push to dockerhub
        if: success() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        env:
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker tag bamzooka/bamzooka_dev:build bamzooka/bamzooka_dev:release
          docker login --username bamzookabuild --password $DOCKERHUB_PASSWORD
          docker push bamzooka/bamzooka_dev:release
