on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  base:
    runs-on: [ubuntu-20.04]
    steps:
      - name: enable experimental docker features
        run: |
          sudo bash -c 'echo "{ \"cgroup-parent\": \"/actions_job\",\"experimental\":true}" > /etc/docker/daemon.json'
          sudo service docker restart
          docker version -f '{{.Server.Experimental}}'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: build base image
        run: |
          cd image && ruby auto_build.rb base
      - name: push to dockerhub
        if: success() && (github.ref == 'refs/heads/main')
        env:
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          TAG=`date +%Y%m%d-%H%M`
          docker tag bamzooka/base:build bamzooka/base:2.0.$TAG
          docker tag bamzooka/base:build bamzooka/base:release
          docker login --username bamzooka --password $DOCKERHUB_PASSWORD
          docker push bamzooka/base:release
          docker push bamzooka/base:2.0.$TAG
